name: Deploy Web App to EC2

on:
  push:
    branches:
      - main  # Deploy when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH agent and add the private key
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 4: SSH into the EC2 instance and clone the Git repository
      - name: SSH into EC2 and clone repo
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            # Navigate to the directory where you want to clone the repository
            cd /var/www/html

            # Clone the Git repository
            git clone https://github.com/sratnadip/githubaction-deploy.git

            # (Optional) If you need to pull the latest changes from the repo
            cd your-repo
            git pull origin main

            # Restart NGINX if necessary or any other application
            sudo systemctl restart nginx
          EOF
