name: Deploy Web App to EC2 (via Bastion Host)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH agent and add the private key
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: SSH into Bastion Host and then SSH into Private Instance
      - name: SSH into Bastion Host and Private EC2
        run: |
          # SSH into the Bastion Host
          ssh -A -o StrictHostKeyChecking=no ubuntu@${{ secrets.SSH_HOST_BASTION }} 
            # SSH into the Private EC2 instance from the Bastion Host
            ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SSH_HOST }} 
            
      - name: Pull repository from GitHub
        run: |
          # Define variables
          REPO_URL="https://github.com/sratnadip/githubaction-deploy.git"  # Replace with your repository URL
          DEST_DIR="/home/ubuntu"  # Replace with your desired destination path

          # Check if the directory exists
          if [ -d "$DEST_DIR/.git" ]; then
              echo "Repository already exists in $DEST_DIR. Pulling the latest changes..."
              cd "$DEST_DIR"
              git pull origin main  # Pull the latest changes
          else
              echo "Cloning the repository to $DEST_DIR..."
              git clone "$REPO_URL" "$DEST_DIR"
          fi
          
         
