name: Deploy Web App to EC2 (via Bastion Host)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH agent and add the private key
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: SSH into Bastion Host and then SSH into Private Instance
      - name: SSH into Bastion Host and Private EC2
        run: |
          # SSH into the Bastion Host
          ssh -A -t -o StrictHostKeyChecking=no ubuntu@${{ secrets.SSH_HOST_BASTION }} << 'EOF'
            # SSH into the Private EC2 instance from the Bastion Host
            ssh -t -o StrictHostKeyChecking=no ubuntu@${{ secrets.SSH_HOST }} << 'INNER_EOF'
              # Deploy your application or clone a repository on the Private EC2 instance
              if [ -d "/var/www/html/githubaction-deploy" ]; then
                echo "Repository already exists. Pulling latest changes..."
                cd /var/www/html/githubaction-deploy
                sudo git pull
              else
                echo "Cloning the repository..."
                sudo mkdir -p /var/www/html
                sudo chown ubuntu:ubuntu /var/www/html
                cd /var/www/html
                sudo git clone https://github.com/sratnadip/githubaction-deploy.git
              fi
            INNER_EOF
          EOF
